#define _CRT_SECURE_NO_WARNINGS
#include<stdio.h>

int main(void)
{
	FILE* pf = NULL;
	unsigned char a[2];
	unsigned short b[1];
	unsigned short c[100000];
	unsigned char d[1];
	int i, j;
	int temp;
	int count;
	int offset;
	pf = fopen("test.gb", "rb");
	if (pf == NULL)
	{
		printf("파일 읽기 에러\n");
		return -1;
	}
	//printf("파일 읽기 성공\n");
	fseek(pf, 0x1cb2e, SEEK_SET);
	offset = -0x4000;
	for (count=0; ftell(pf) < 0x1dd67; count++ )
	{
		fread(&c[count], sizeof(short), 1, pf);
		if (c[count] == 0)
			offset += 0x4000;
		c[count] += offset;
		printf("%x: %x\n", count,c[count]);
	}
	c[count] = 0xffff;
	printf(".org 0x1cb2e\n");
	for (i = 0; i < count; i++)
	{
		printf("dh (text_%X)%%0x4000\n",i);
	}

	fseek(pf, 0x70000, SEEK_SET);
	for (i=0; ftell(pf) < 0x7ffff, i<count;i++ )
	{
		fseek(pf, 0x70000+c[i], SEEK_SET);
		printf(".org 0x%x\n", 0x70000 + c[i]);
		printf("text_%X:\n", i);
		while (c[i] == c[i + 1])
		{
			printf("text_%X:\n", ++i);
			if (i > count) break;
		}
		int kanji=0;
		int bigfont = 0;
		int raw = 2;
		printf("db ");
		while (ftell(pf) < 0x70000 + c[i+1])
		{
			fread(d, sizeof(char), 1, pf);

			if (raw > 0)
			{
				printf("0x%X, ", d[0]);
				raw--;
			}
			else if (bigfont == 1)
			{
				switch (d[0])
				{
				case 0x00:	printf("\"<タ>\", ");	break;
				case 0x01:	printf("\"<ダ>\", ");	break;
				case 0x02:	printf("\"<ゲ>\", ");	break;
				case 0x03:	printf("\"<ッ>\", ");	break;
				case 0x04:	printf("\"<！>\", ");	break;
				case 0x05:	printf("\"<？>\", ");	break;
				case 0x06:	printf("\"<な>\", ");	break;
				case 0x07:	printf("\"<に>\", ");	break;
				case 0x08:	printf("\"<一>\", ");	break;
				case 0x09:	printf("\"<っ>\", ");	break;
				case 0x0A:	printf("\"<許>\", ");	break;
				case 0x0B:	printf("\"<せ>\", ");	break;
				case 0x0C:	printf("\"<ん>\", ");	break;
				case 0x0D:	printf("\"<ス>\", ");	break;
				case 0x0E:	printf("\"<ポ>\", ");	break;
				case 0x0F:	printf("\"<ア>\", ");	break;
				case 0x10:	printf("\"<～>\", ");	break;
				case 0x11:	printf("\"<レ>\", ");	break;
				case 0x12:	printf("\"<Z>\", ");	break;
				case 0x13:	printf("\"<‥>\", ");	break;
				case 0x14:	printf("\"<ギ>\", ");	break;
				case 0x15:	printf("\"<ャ>\", ");	break;
				case 0x16:	printf("\"<ぐ>\", ");	break;
				case 0x17:	printf("\"<わ>\", ");	break;
				case 0x18:	printf("\"<同>\", ");	break;
				case 0x19:	printf("\"<じ>\", ");	break;
				case 0x1A:	printf("\"<の>\", ");	break;
				case 0x1B:	printf("\"<し>\", ");	break;
				case 0x1C:	printf("\"<ハ>\", ");	break;
				case 0x1D:	printf("\"<ウ>\", ");	break;
				case 0x1E:	printf("\"<ワ>\", ");	break;
				case 0x1F:	printf("\"<ぁ>\", ");	break;

				case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
				case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
				case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
				case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
				case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
				case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
				case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
				case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
				case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
				case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
				case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
				case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
				case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
				case 0xFE:  printf("\" \", ");	raw = 0; break;
				case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;
				default:    printf("0x%X, ", d[0]);
				}
			}
			else if (kanji == 0)
			{
				switch (d[0])
				{
				case 0x00:	printf("\" \", ");	break;
				case 0x01:	printf("\"이\", ");	break;
				case 0x02:	printf("\"다\", ");	break;
				case 0x03:	printf("\"는\", ");	break;
				case 0x04:	printf("\"지\", ");	break;
				case 0x05:	printf("\"가\", ");	break;
				case 0x06:	printf("\"어\", ");	break;
				case 0x07:	printf("\"을\", ");	break;
				case 0x08:	printf("\"에\", ");	break;
				case 0x09:	printf("\"하\", ");	break;
				case 0x0A:	printf("\"아\", ");	break;
				case 0x0B:	printf("\"로\", ");	break;
				case 0x0C:	printf("\"리\", ");	break;
				case 0x0D:	printf("\"그\", ");	break;
				case 0x0E:	printf("\"라\", ");	break;
				case 0x0F:	printf("\"고\", ");	break;
				case 0x10:	printf("\"니\", ");	break;
				case 0x11:	printf("\"게\", ");	break;
				case 0x12:	printf("\"자\", ");	break;
				case 0x13:	printf("\"의\", ");	break;
				case 0x14:	printf("\"있\", ");	break;
				case 0x15:	printf("\"요\", ");	break;
				case 0x16:	printf("\"도\", ");	break;
				case 0x17:	printf("\"나\", ");	break;
				case 0x18:	printf("\"은\", ");	break;
				case 0x19:	printf("\"으\", ");	break;
				case 0x1A:	printf("\"를\", ");	break;
				case 0x1B:	printf("\"사\", ");	break;
				case 0x1C:	printf("\"만\", ");	break;
				case 0x1D:	printf("\"서\", ");	break;
				case 0x1E:	printf("\"마\", ");	break;
				case 0x1F:	printf("\"구\", ");	break;
				case 0x20:	printf("\"수\", ");	break;
				case 0x21:	printf("\"해\", ");	break;
				case 0x22:	printf("\"한\", ");	break;
				case 0x23:	printf("\"주\", ");	break;
				case 0x24:	printf("\"스\", ");	break;
				case 0x25:	printf("\"시\", ");	break;
				case 0x26:	printf("\"드\", ");	break;
				case 0x27:	printf("\"기\", ");	break;
				case 0x28:	printf("\"왕\", ");	break;
				case 0x29:	printf("\"야\", ");	break;
				case 0x2A:	printf("\"들\", ");	break;
				case 0x2B:	printf("\"오\", ");	break;
				case 0x2C:	printf("\"것\", ");	break;
				case 0x2D:	printf("\"금\", ");	break;
				case 0x2E:	printf("\"없\", ");	break;
				case 0x2F:	printf("\"일\", ");	break;
				case 0x30:	printf("\"모\", ");	break;
				case 0x31:	printf("\"면\", ");	break;
				case 0x32:	printf("\"거\", ");	break;
				case 0x33:	printf("\"개\", ");	break;
				case 0x34:	printf("\"인\", ");	break;
				case 0x35:	printf("\"님\", ");	break;
				case 0x36:	printf("\"겠\", ");	break;
				case 0x37:	printf("\"군\", ");	break;
				case 0x38:	printf("\"습\", ");	break;
				case 0x39:	printf("\"무\", ");	break;
				case 0x3A:	printf("\"러\", ");	break;
				case 0x3B:	printf("\"우\", ");	break;
				case 0x3C:	printf("\"까\", ");	break;
				case 0x3D:	printf("\"대\", ");	break;
				case 0x3E:	printf("\"네\", ");	break;
				case 0x3F:	printf("\"데\", ");	break;
				case 0x40:	printf("\"와\", ");	break;
				case 0x41:	printf("\"말\", ");	break;
				case 0x42:	printf("\"건\", ");	break;
				case 0x43:	printf("\"두\", ");	break;
				case 0x44:	printf("\"처\", ");	break;
				case 0x45:	printf("\"안\", ");	break;
				case 0x46:	printf("\"전\", ");	break;
				case 0x47:	printf("\"보\", ");	break;
				case 0x48:	printf("\"신\", ");	break;
				case 0x49:	printf("\"산\", ");	break;
				case 0x4A:	printf("\"않\", ");	break;
				case 0x4B:	printf("\"내\", ");	break;
				case 0x4C:	printf("\"었\", ");	break;
				case 0x4D:	printf("\"상\", ");	break;
				case 0x4E:	printf("\"려\", ");	break;
				case 0x4F:	printf("\"같\", ");	break;
				case 0x50:	printf("\"저\", ");	break;
				case 0x51:	printf("\"여\", ");	break;
				case 0x52:	printf("\"뭐\", ");	break;
				case 0x53:	printf("\"정\", ");	break;
				case 0x54:	printf("\"북\", ");	break;
				case 0x55:	printf("\"음\", ");	break;
				case 0x56:	printf("\"세\", ");	break;
				case 0x57:	printf("\"입\", ");	break;
				case 0x58:	printf("\"간\", ");	break;
				case 0x59:	printf("\"장\", ");	break;
				case 0x5A:	printf("\"되\", ");	break;
				case 0x5B:	printf("\"위\", ");	break;
				case 0x5C:	printf("\"린\", ");	break;
				case 0x5D:	printf("\"물\", ");	break;
				case 0x5E:	printf("\"돌\", ");	break;
				case 0x5F:	printf("\"런\", ");	break;
				case 0x60:	printf("\"굴\", ");	break;
				case 0x61:	printf("\"알\", ");	break;
				case 0x62:	printf("\"제\", ");	break;
				case 0x63:	printf("\"동\", ");	break;
				case 0x64:	printf("\"용\", ");	break;
				case 0x65:	printf("\"진\", ");	break;
				case 0x66:	printf("\"공\", ");	break;
				case 0x67:	printf("\"치\", ");	break;
				case 0x68:	printf("\"활\", ");	break;
				case 0x69:	printf("\"했\", ");	break;
				case 0x6A:	printf("\"과\", ");	break;
				case 0x6B:	printf("\"녀\", ");	break;
				case 0x6C:	printf("\"래\", ");	break;
				case 0x6D:	printf("\"비\", ");	break;
				case 0x6E:	printf("\"바\", ");	break;
				case 0x6F:	printf("\"좋\", ");	break;
				case 0x70:	printf("\"히\", ");	break;
				case 0x71:	printf("\"분\", ");	break;
				case 0x72:	printf("\"프\", ");	break;
				case 0x73:	printf("\"난\", ");	break;
				case 0x74:	printf("\"럼\", ");	break;
				case 0x75:	printf("\"렇\", ");	break;
				case 0x76:	printf("\"걸\", ");	break;
				case 0x77:	printf("\"방\", ");	break;
				case 0x78:	printf("\"소\", ");	break;
				case 0x79:	printf("\"곳\", ");	break;
				case 0x7A:	printf("\"너\", ");	break;
				case 0x7B:	printf("\"문\", ");	break;
				case 0x7C:	printf("\"미\", ");	break;
				case 0x7D:	printf("\"던\", ");	break;
				case 0x7E:	printf("\"든\", ");	break;
				case 0x7F:	printf("\"람\", ");	break;
				case 0x80:	printf("\"버\", ");	break;
				case 0x81:	printf("\"트\", ");	break;
				case 0x82:	printf("\"약\", ");	break;
				case 0x83:	printf("\"온\", ");	break;
				case 0x84:	printf("\"당\", ");	break;
				case 0x85:	printf("\"레\", ");	break;
				case 0x86:	printf("\"맘\", ");	break;
				case 0x87:	printf("\"석\", ");	break;
				case 0x88:	printf("\"았\", ");	break;
				case 0x89:	printf("\"호\", ");	break;
				case 0x8A:	printf("\"돈\", ");	break;
				case 0x8B:	printf("\"르\", ");	break;
				case 0x8C:	printf("\"실\", ");	break;
				case 0x8D:	printf("\"져\", ");	break;
				case 0x8E:	printf("\"생\", ");	break;
				case 0x8F:	printf("\"궁\", ");	break;
				case 0x90:	printf("\"냐\", ");	break;
				case 0x91:	printf("\"봐\", ");	break;
				case 0x92:	printf("\"종\", ");	break;
				case 0x93:	printf("\"길\", ");	break;
				case 0x94:	printf("\"께\", ");	break;
				case 0x95:	printf("\"놈\", ");	break;
				case 0x96:	printf("\"디\", ");	break;
				case 0x97:	printf("\"감\", ");	break;
				case 0x98:	printf("\"더\", ");	break;
				case 0x99:	printf("\"명\", ");	break;
				case 0x9A:	printf("\"발\", ");	break;
				case 0x9B:	printf("\"변\", ");	break;
				case 0x9C:	printf("\"병\", ");	break;
				case 0x9D:	printf("\"잘\", ");	break;
				case 0x9E:	printf("\"적\", ");	break;
				case 0x9F:	printf("\"찾\", ");	break;
				case 0xA0:	printf("\"~\", ");	break;
				case 0xA1:	printf("\"！\", ");	break;
				case 0xA2:	printf("\"？\", ");	break;
				case 0xA3:	printf("\"－\", ");	break;
				case 0xA4:	printf("\".\", ");	break;
				case 0xA5:	printf("\"‥\", ");	break;
				case 0xA6:	printf("\"♡\", ");	break;
				case 0xA7:	printf("\"&\", ");	break;
				case 0xA8:	printf("\"、\", ");	break;
				case 0xA9:	printf("\"。\", ");	break;
				case 0xAA:	printf("\"(\", ");	break;
				case 0xAB:	printf("\")\", ");	break;
				case 0xAC:	printf("\"○\", ");	break;
				case 0xAD:	printf("\"×\", ");	break;
				case 0xAE:	printf("\"△\", ");	break;
				case 0xAF:	printf("\"_\", ");	break;
				case 0xB0:	printf("\"A\", ");	break;
				case 0xB1:	printf("\"B\", ");	break;
				case 0xB2:	printf("\"C\", ");	break;
				case 0xB3:	printf("\"D\", ");	break;
				case 0xB4:	printf("\"E\", ");	break;
				case 0xB5:	printf("\"F\", ");	break;
				case 0xB6:	printf("\"G\", ");	break;
				case 0xB7:	printf("\"H\", ");	break;
				case 0xB8:	printf("\"I\", ");	break;
				case 0xB9:	printf("\"J\", ");	break;
				case 0xBA:	printf("\"K\", ");	break;
				case 0xBB:	printf("\"L\", ");	break;
				case 0xBC:	printf("\"M\", ");	break;
				case 0xBD:	printf("\"N\", ");	break;
				case 0xBE:	printf("\"O\", ");	break;
				case 0xBF:	printf("\"P\", ");	break;
				case 0xC0:	printf("\"Q\", ");	break;
				case 0xC1:	printf("\"R\", ");	break;
				case 0xC2:	printf("\"S\", ");	break;
				case 0xC3:	printf("\"T\", ");	break;
				case 0xC4:	printf("\"U\", ");	break;
				case 0xC5:	printf("\"V\", ");	break;
				case 0xC6:	printf("\"W\", ");	break;
				case 0xC7:	printf("\"X\", ");	break;
				case 0xC8:	printf("\"Y\", ");	break;
				case 0xC9:	printf("\"Z\", ");	break;
				case 0xCA:	printf("\"<-1>\", ");	break;
				case 0xCB:	printf("\"<-2>\", ");	break;
				case 0xCC:	printf("\"<-3>\", ");	break;
				case 0xCD:	printf("\"▼\", ");	break;
				case 0xCE:	printf("\"「\", ");	break;
				case 0xCF:	printf("\"」\", ");	break;
				case 0xD0:	printf("\"0\", ");	break;
				case 0xD1:	printf("\"1\", ");	break;
				case 0xD2:	printf("\"2\", ");	break;
				case 0xD3:	printf("\"3\", ");	break;
				case 0xD4:	printf("\"4\", ");	break;
				case 0xD5:	printf("\"5\", ");	break;
				case 0xD6:	printf("\"6\", ");	break;
				case 0xD7:	printf("\"7\", ");	break;
				case 0xD8:	printf("\"8\", ");	break;
				case 0xD9:	printf("\"9\", ");	break;
				case 0xDA:	printf("\"크\", ");	break;
				case 0xDB:	printf("\"각\", ");	break;
				case 0xDC:	printf("\"먹\", ");	break;
				case 0xDD:	printf("\"받\", ");	break;
				case 0xDE:	printf("\"워\", ");	break;
				case 0xDF:	printf("\"째\", ");	break;
				case 0xE0:	printf("\"쪽\", ");	break;
				case 0xE1:	printf("\"뱀\", ");	break;
				case 0xE2:	printf("\"울\", ");	break;
				case 0xE3:	printf("\"때\", ");	break;
				case 0xE4:	printf("\"복\", ");	break;
				case 0xE5:	printf("\"십\", ");	break;
				case 0xE6:	printf("\"역\", ");	break;
				case 0xE7:	printf("\"행\", ");	break;
				case 0xE8:	printf("\"선\", ");	break;
				case 0xE9:	printf("\"얼\", ");	break;
				case 0xEA:	printf("\"유\", ");	break;
				case 0xEB:	printf("\"갈\", ");	break;
				case 0xEC:	printf("\"록\", ");	break;
				case 0xED:	printf("\"막\", ");	break;
				case 0xEE:	kanji = 1;	break;
				case 0xEF:	kanji = 2;	break;
				case 0xF0:	kanji = 3;	break;

				case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
				case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
				case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
				case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
				case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
				case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
				case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
				case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
				case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
				case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
				case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
				case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
				case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
				case 0xFE:  printf("\" \", ");	raw = 0; break;
				case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;

				default:    printf("0x%X, ", d[0]);
				}
			}
			else if (kanji == 1)
			{
			switch (d[0])
			{
			case 0x00:	printf("\"원\", ");	break;
			case 0x01:	printf("\"쳐\", ");	break;
			case 0x02:	printf("\"타\", ");	break;
			case 0x03:	printf("\"직\", ");	break;
			case 0x04:	printf("\"터\", ");	break;
			case 0x05:	printf("\"화\", ");	break;
			case 0x06:	printf("\"후\", ");	break;
			case 0x07:	printf("\"긴\", ");	break;
			case 0x08:	printf("\"싶\", ");	break;
			case 0x09:	printf("\"잡\", ");	break;
			case 0x0A:	printf("\"천\", ");	break;
			case 0x0B:	printf("\"떻\", ");	break;
			case 0x0C:	printf("\"봄\", ");	break;
			case 0x0D:	printf("\"연\", ");	break;
			case 0x0E:	printf("\"운\", ");	break;
			case 0x0F:	printf("\"힘\", ");	break;
			case 0x10:	printf("\"성\", ");	break;
			case 0x11:	printf("\"혀\", ");	break;
			case 0x12:	printf("\"계\", ");	break;
			case 0x13:	printf("\"박\", ");	break;
			case 0x14:	printf("\"빨\", ");	break;
			case 0x15:	printf("\"파\", ");	break;
			case 0x16:	printf("\"렸\", ");	break;
			case 0x17:	printf("\"셨\", ");	break;
			case 0x18:	printf("\"쓰\", ");	break;
			case 0x19:	printf("\"잖\", ");	break;
			case 0x1A:	printf("\"빙\", ");	break;
			case 0x1B:	printf("\"식\", ");	break;
			case 0x1C:	printf("\"열\", ");	break;
			case 0x1D:	printf("\"온\", ");	break;
			case 0x1E:	printf("\"국\", ");	break;
			case 0x1F:	printf("\"번\", ");	break;
			case 0x20:	printf("\"베\", ");	break;
			case 0x21:	printf("\"앗\", ");	break;
			case 0x22:	printf("\"뎀\", ");	break;
			case 0x23:	printf("\"회\", ");	break;
			case 0x24:	printf("\"따\", ");	break;
			case 0x25:	printf("\"슨\", ");	break;
			case 0x26:	printf("\"왔\", ");	break;
			case 0x27:	printf("\"집\", ");	break;
			case 0x28:	printf("\"친\", ");	break;
			case 0x29:	printf("\"ㅐ\", ");	break;
			case 0x2A:	printf("\"피\", ");	break;
			case 0x2B:	printf("\"합\", ");	break;
			case 0x2C:	printf("\"단\", ");	break;
			case 0x2D:	printf("\"뜨\", ");	break;
			case 0x2E:	printf("\"못\", ");	break;
			case 0x2F:	printf("\"뭔\", ");	break;
			case 0x30:	printf("\"살\", ");	break;
			case 0x31:	printf("\"속\", ");	break;
			case 0x32:	printf("\"테\", ");	break;
			case 0x33:	printf("\"티\", ");	break;
			case 0x34:	printf("\"겨\", ");	break;
			case 0x35:	printf("\"남\", ");	break;
			case 0x36:	printf("\"누\", ");	break;
			case 0x37:	printf("\"느\", ");	break;
			case 0x38:	printf("\"딸\", ");	break;
			case 0x39:	printf("\"릴\", ");	break;
			case 0x3A:	printf("\"망\", ");	break;
			case 0x3B:	printf("\"딱\", ");	break;
			case 0x3C:	printf("\"편\", ");	break;
			case 0x3D:	printf("\"글\", ");	break;
			case 0x3E:	printf("\"딩\", ");	break;
			case 0x3F:	printf("\"또\", ");	break;
			case 0x40:	printf("\"밀\", ");	break;
			case 0x41:	printf("\"북\", ");	break;
			case 0x42:	printf("\"움\", ");	break;
			case 0x43:	printf("\"응\", ");	break;
			case 0x44:	printf("\"좀\", ");	break;
			case 0x45:	printf("\"줘\", ");	break;
			case 0x46:	printf("\"키\", ");	break;
			case 0x47:	printf("\"헤\", ");	break;
			case 0x48:	printf("\"됐\", ");	break;
			case 0x49:	printf("\"른\", ");	break;
			case 0x4A:	printf("\"맞\", ");	break;
			case 0x4B:	printf("\"심\", ");	break;
			case 0x4C:	printf("\"앞\", ");	break;
			case 0x4D:	printf("\"잠\", ");	break;
			case 0x4E:	printf("\"조\", ");	break;
			case 0x4F:	printf("\"푸\", ");	break;
			case 0x50:	printf("\"회\", ");	break;
			case 0x51:	printf("\"검\", ");	break;
			case 0x52:	printf("\"격\", ");	break;
			case 0x53:	printf("\"링\", ");	break;
			case 0x54:	printf("\"몸\", ");	break;
			case 0x55:	printf("\"배\", ");	break;
			case 0x56:	printf("\"법\", ");	break;
			case 0x57:	printf("\"점\", ");	break;
			case 0x58:	printf("\"통\", ");	break;
			case 0x59:	printf("\"튼\", ");	break;
			case 0x5A:	printf("\"틀\", ");	break;
			case 0x5B:	printf("\"함\", ");	break;
			case 0x5C:	printf("\"힐\", ");	break;
			case 0x5D:	printf("\"났\", ");	break;
			case 0x5E:	printf("\"된\", ");	break;
			case 0x5F:	printf("\"채\", ");	break;
			case 0x60:	printf("\"케\", ");	break;
			case 0x61:	printf("\"큰\", ");	break;
			case 0x62:	printf("\"결\", ");	break;
			case 0x63:	printf("\"괴\", ");	break;
			case 0x64:	printf("\"날\", ");	break;
			case 0x65:	printf("\"란\", ");	break;
			case 0x66:	printf("\"밖\", ");	break;
			case 0x67:	printf("\"작\", ");	break;
			case 0x68:	printf("\"줄\", ");	break;
			case 0x69:	printf("\"렌\", ");	break;
			case 0x6A:	printf("\"불\", ");	break;
			case 0x6B:	printf("\"였\", ");	break;
			case 0x6C:	printf("\"예\", ");	break;
			case 0x6D:	printf("\"잼\", ");	break;
			case 0x6E:	printf("\"찌\", ");	break;
			case 0x6F:	printf("\"침\", ");	break;
			case 0x70:	printf("\"커\", ");	break;
			case 0x71:	printf("\"끝\", ");	break;
			case 0x72:	printf("\"례\", ");	break;
			case 0x73:	printf("\"설\", ");	break;
			case 0x74:	printf("\"씨\", ");	break;
			case 0x75:	printf("\"질\", ");	break;
			case 0x76:	printf("\"관\", ");	break;
			case 0x77:	printf("\"굉\", ");	break;
			case 0x78:	printf("\"목\", ");	break;
			case 0x79:	printf("\"빠\", ");	break;
			case 0x7A:	printf("\"싸\", ");	break;
			case 0x7B:	printf("\"왜\", ");	break;
			case 0x7C:	printf("\"중\", ");	break;
			case 0x7D:	printf("\"짓\", ");	break;
			case 0x7E:	printf("\"착\", ");	break;
			case 0x7F:	printf("\"참\", ");	break;
			case 0x80:	printf("\"클\", ");	break;
			case 0x81:	printf("\"폰\", ");	break;
			case 0x82:	printf("\"겁\", ");	break;
			case 0x83:	printf("\"근\", ");	break;
			case 0x84:	printf("\"꿈\", ");	break;
			case 0x85:	printf("\"놓\", ");	break;
			case 0x86:	printf("\"뇨\", ");	break;
			case 0x87:	printf("\"돼\", ");	break;
			case 0x88:	printf("\"둔\", ");	break;
			case 0x89:	printf("\"머\", ");	break;
			case 0x8A:	printf("\"써\", ");	break;
			case 0x8B:	printf("\"철\", ");	break;
			case 0x8C:	printf("\"출\", ");	break;
			case 0x8D:	printf("\"포\", ");	break;
			case 0x8E:	printf("\"질\", ");	break;
			case 0x8F:	printf("\"갔\", ");	break;
			case 0x90:	printf("\"강\", ");	break;
			case 0x91:	printf("\"교\", ");	break;
			case 0x92:	printf("\"꾹\", ");	break;
			case 0x93:	printf("\"독\", ");	break;
			case 0x94:	printf("\"될\", ");	break;
			case 0x95:	printf("\"듣\", ");	break;
			case 0x96:	printf("\"력\", ");	break;
			case 0x97:	printf("\"롤\", ");	break;
			case 0x98:	printf("\"림\", ");	break;
			case 0x99:	printf("\"많\", ");	break;
			case 0x9A:	printf("\"맛\", ");	break;
			case 0x9B:	printf("\"볼\", ");	break;
			case 0x9C:	printf("\"쇠\", ");	break;
			case 0x9D:	printf("\"옥\", ");	break;
			case 0x9E:	printf("\"재\", ");	break;
			case 0x9F:	printf("\"죽\", ");	break;
			case 0xA0:	printf("\"체\", ");	break;
			case 0xA1:	printf("\"컨\", ");	break;
			case 0xA2:	printf("\"텐\", ");	break;
			case 0xA3:	printf("\"갑\", ");	break;
			case 0xA4:	printf("\"꺽\", ");	break;
			case 0xA5:	printf("\"꿀\", ");	break;
			case 0xA6:	printf("\"둘\", ");	break;
			case 0xA7:	printf("\"름\", ");	break;
			case 0xA8:	printf("\"뿐\", ");	break;
			case 0xA9:	printf("\"셔\", ");	break;
			case 0xAA:	printf("\"순\", ");	break;
			case 0xAB:	printf("\"숭\", ");	break;
			case 0xAC:	printf("\"악\", ");	break;
			case 0xAD:	printf("\"완\", ");	break;
			case 0xAE:	printf("\"졌\", ");	break;
			case 0xAF:	printf("\"즈\", ");	break;
			case 0xB0:	printf("\"찮\", ");	break;
			case 0xB1:	printf("\"초\", ");	break;
			case 0xB2:	printf("\"컥\", ");	break;
			case 0xB3:	printf("\"켜\", ");	break;
			case 0xB4:	printf("\"코\", ");	break;
			case 0xB5:	printf("\"킬\", ");	break;
			case 0xB6:	printf("\"겔\", ");	break;
			case 0xB7:	printf("\"경\", ");	break;
			case 0xB8:	printf("\"괜\", ");	break;
			case 0xB9:	printf("\"둑\", ");	break;
			case 0xBA:	printf("\"롭\", ");	break;
			case 0xBB:	printf("\"료\", ");	break;
			case 0xBC:	printf("\"맡\", ");	break;
			case 0xBD:	printf("\"매\", ");	break;
			case 0xBE:	printf("\"멋\", ");	break;
			case 0xBF:	printf("\"반\", ");	break;
			case 0xC0:	printf("\"벱\", ");	break;
			case 0xC1:	printf("\"빰\", ");	break;
			case 0xC2:	printf("\"억\", ");	break;
			case 0xC3:	printf("\"외\", ");	break;
			case 0xC4:	printf("\"항\", ");	break;
			case 0xC5:	printf("\"혹\", ");	break;
			case 0xC6:	printf("\"걱\", ");	break;
			case 0xC7:	printf("\"견\", ");	break;
			case 0xC8:	printf("\"깨\", ");	break;
			case 0xC9:	printf("\"노\", ");	break;
			case 0xCA:	printf("\"눈\", ");	break;
			case 0xCB:	printf("\"달\", ");	break;
			case 0xCC:	printf("\"떤\", ");	break;
			case 0xCD:	printf("\"뛰\", ");	break;
			case 0xCE:	printf("\"메\", ");	break;
			case 0xCF:	printf("\"물\", ");	break;
			case 0xD0:	printf("\"블\", ");	break;
			case 0xD1:	printf("\"섬\", ");	break;
			case 0xD2:	printf("\"손\", ");	break;
			case 0xD3:	printf("\"술\", ");	break;
			case 0xD4:	printf("\"싫\", ");	break;
			case 0xD5:	printf("\"절\", ");	break;
			case 0xD6:	printf("\"젠\", ");	break;
			case 0xD7:	printf("\"죠\", ");	break;
			case 0xD8:	printf("\"최\", ");	break;
			case 0xD9:	printf("\"추\", ");	break;
			case 0xDA:	printf("\"퇴\", ");	break;
			case 0xDB:	printf("\"핫\", ");	break;
			case 0xDC:	printf("\"혼\", ");	break;
			case 0xDD:	printf("\"귀\", ");	break;
			case 0xDE:	printf("\"깐\", ");	break;
			case 0xDF:	printf("\"낼\", ");	break;
			case 0xE0:	printf("\"냥\", ");	break;
			case 0xE1:	printf("\"넌\", ");	break;
			case 0xE2:	printf("\"넣\", ");	break;
			case 0xE3:	printf("\"녹\", ");	break;
			case 0xE4:	printf("\"덕\", ");	break;
			case 0xE5:	printf("\"땅\", ");	break;
			case 0xE6:	printf("\"떠\", ");	break;
			case 0xE7:	printf("\"럽\", ");	break;
			case 0xE8:	printf("\"령\", ");	break;
			case 0xE9:	printf("\"루\", ");	break;
			case 0xEA:	printf("\"몬\", ");	break;
			case 0xEB:	printf("\"새\", ");	break;
			case 0xEC:	printf("\"언\", ");	break;
			case 0xED:	printf("\"엔\", ");	break;
			case 0xEE:	kanji = 1;break;
			case 0xEF:	kanji = 2;	break;
			case 0xF0:	kanji = 3;	break;

			case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
			case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
			case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
			case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
			case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
			case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
			case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
			case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
			case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
			case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
			case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
			case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
			case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
			case 0xFE:  printf("\" \", ");	raw = 0; break;
			case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;

			default:    printf("0x%X, ", d[0]);
			}
			kanji = 0;
			}
			else if (kanji == 2)
			{
			switch (d[0])
			{
			case 0x00:	printf("\"임\", ");	break;
			case 0x01:	printf("\"준\", ");	break;
			case 0x02:	printf("\"쩐\", ");	break;
			case 0x03:	printf("\"차\", ");	break;
			case 0x04:	printf("\"출\", ");	break;
			case 0x05:	printf("\"톤\", ");	break;
			case 0x06:	printf("\"평\", ");	break;
			case 0x07:	printf("\"향\", ");	break;
			case 0x08:	printf("\"흐\", ");	break;
			case 0x09:	printf("\"골\", ");	break;
			case 0x0A:	printf("\"답\", ");	break;
			case 0x0B:	printf("\"떨\", ");	break;
			case 0x0C:	printf("\"락\", ");	break;
			case 0x0D:	printf("\"밥\", ");	break;
			case 0x0E:	printf("\"벌\", ");	break;
			case 0x0F:	printf("\"벽\", ");	break;
			case 0x10:	printf("\"양\", ");	break;
			case 0x11:	printf("\"엄\", ");	break;
			case 0x12:	printf("\"짜\", ");	break;
			case 0x13:	printf("\"쨋\", ");	break;
			case 0x14:	printf("\"쩌\", ");	break;
			case 0x15:	printf("\"책\", ");	break;
			case 0x16:	printf("\"칫\", ");	break;
			case 0x17:	printf("\"쿡\", ");	break;
			case 0x18:	printf("\"택\", ");	break;
			case 0x19:	printf("\"풀\", ");	break;
			case 0x1A:	printf("\"갖\", ");	break;
			case 0x1B:	printf("\"넘\", ");	break;
			case 0x1C:	printf("\"늘\", ");	break;
			case 0x1D:	printf("\"둗\", ");	break;
			case 0x1E:	printf("\"딘\", ");	break;
			case 0x1F:	printf("\"브\", ");	break;
			case 0x20:	printf("\"빛\", ");	break;
			case 0x21:	printf("\"애\", ");	break;
			case 0x22:	printf("\"옳\", ");	break;
			case 0x23:	printf("\"웃\", ");	break;
			case 0x24:	printf("\"윽\", ");	break;
			case 0x25:	printf("\"취\", ");	break;
			case 0x26:	printf("\"측\", ");	break;
			case 0x27:	printf("\"카\", ");	break;
			case 0x28:	printf("\"톱\", ");	break;
			case 0x29:	printf("\"투\", ");	break;
			case 0x2A:	printf("\"틈\", ");	break;
			case 0x2B:	printf("\"판\", ");	break;
			case 0x2C:	printf("\"팔\", ");	break;
			case 0x2D:	printf("\"험\", ");	break;
			case 0x2E:	printf("\"현\", ");	break;
			case 0x2F:	printf("\"훌\", ");	break;
			case 0x30:	printf("\"흠\", ");	break;
			case 0x31:	printf("\"권\", ");	break;
			case 0x32:	printf("\"꼬\", ");	break;
			case 0x33:	printf("\"닌\", ");	break;
			case 0x34:	printf("\"덩\", ");	break;
			case 0x35:	printf("\"둬\", ");	break;
			case 0x36:	printf("\"멍\", ");	break;
			case 0x37:	printf("\"믿\", ");	break;
			case 0x38:	printf("\"빌\", ");	break;
			case 0x39:	printf("\"색\", ");	break;
			case 0x3A:	printf("\"숨\", ");	break;
			case 0x3B:	printf("\"쉬\", ");	break;
			case 0x3C:	printf("\"얻\", ");	break;
			case 0x3D:	printf("\"옆\", ");	break;
			case 0x3E:	printf("\"왠\", ");	break;
			case 0x3F:	printf("\"욕\", ");	break;
			case 0x40:	printf("\"잇\", ");	break;
			case 0x41:	printf("\"쫌\", ");	break;
			case 0x42:	printf("\"칠\", ");	break;
			case 0x43:	printf("\"탈\", ");	break;
			case 0x44:	printf("\"퍼\", ");	break;
			case 0x45:	printf("\"곡\", ");	break;
			case 0x46:	printf("\"곧\", ");	break;
			case 0x47:	printf("\"괭\", ");	break;
			case 0x48:	printf("\"꼭\", ");	break;
			case 0x49:	printf("\"끼\", ");	break;
			case 0x4A:	printf("\"낌\", ");	break;
			case 0x4B:	printf("\"낸\", ");	break;
			case 0x4C:	printf("\"냈\", ");	break;
			case 0x4D:	printf("\"놀\", ");	break;
			case 0x4E:	printf("\"놔\", ");	break;
			case 0x4F:	printf("\"덤\", ");	break;
			case 0x50:	printf("\"듯\", ");	break;
			case 0x51:	printf("\"뜻\", ");	break;
			case 0x52:	printf("\"랐\", ");	break;
			case 0x53:	printf("\"련\", ");	break;
			case 0x54:	printf("\"밤\", ");	break;
			case 0x55:	printf("\"밴\", ");	break;
			case 0x56:	printf("\"빼\", ");	break;
			case 0x57:	printf("\"뿌\", ");	break;
			case 0x58:	printf("\"삼\", ");	break;
			case 0x59:	printf("\"송\", ");	break;
			case 0x5A:	printf("\"쇼\", ");	break;
			case 0x5B:	printf("\"씀\", ");	break;
			case 0x5C:	printf("\"씩\", ");	break;
			case 0x5D:	printf("\"업\", ");	break;
			case 0x5E:	printf("\"옷\", ");	break;
			case 0x5F:	printf("\"족\", ");	break;
			case 0x60:	printf("\"좌\", ");	break;
			case 0x61:	printf("\"줬\", ");	break;
			case 0x62:	printf("\"쩔\", ");	break;
			case 0x63:	printf("\"찬\", ");	break;
			case 0x64:	printf("\"창\", ");	break;
			case 0x65:	printf("\"청\", ");	break;
			case 0x66:	printf("\"충\", ");	break;
			case 0x67:	printf("\"층\", ");	break;
			case 0x68:	printf("\"형\", ");	break;
			case 0x69:	printf("\"확\", ");	break;
			case 0x6A:	printf("\"환\", ");	break;
			case 0x6B:	printf("\"활\", ");	break;
			case 0x6C:	printf("\"획\", ");	break;
			case 0x6D:	printf("\"힌\", ");	break;
			case 0x6E:	printf("\"겼\", ");	break;
			case 0x6F:	printf("\"곤\", ");	break;
			case 0x70:	printf("\"긋\", ");	break;
			case 0x71:	printf("\"깊\", ");	break;
			case 0x72:	printf("\"꾸\", ");	break;
			case 0x73:	printf("\"능\", ");	break;
			case 0x74:	printf("\"뵙\", ");	break;
			case 0x75:	printf("\"뒤\", ");	break;
			case 0x76:	printf("\"럴\", ");	break;
			case 0x77:	printf("\"륵\", ");	break;
			case 0x78:	printf("\"맥\", ");	break;
			case 0x79:	printf("\"며\", ");	break;
			case 0x7A:	printf("\"묻\", ");	break;
			case 0x7B:	printf("\"벼\", ");	break;
			case 0x7C:	printf("\"별\", ");	break;
			case 0x7D:	printf("\"봤\", ");	break;
			case 0x7E:	printf("\"숲\", ");	break;
			case 0x7F:	printf("\"썩\", ");	break;
			case 0x80:	printf("\"쓸\", ");	break;
			case 0x81:	printf("\"얌\", ");	break;
			case 0x82:	printf("\"얘\", ");	break;
			case 0x83:	printf("\"영\", ");	break;
			case 0x84:	printf("\"옳\", ");	break;
			case 0x85:	printf("\"왼\", ");	break;
			case 0x86:	printf("\"욱\", ");	break;
			case 0x87:	printf("\"익\", ");	break;
			case 0x88:	printf("\"잃\", ");	break;
			case 0x89:	printf("\"잔\", ");	break;
			case 0x8A:	printf("\"쟁\", ");	break;
			case 0x8B:	printf("\"즉\", ");	break;
			case 0x8C:	printf("\"짐\", ");	break;
			case 0x8D:	printf("\"쩍\", ");	break;
			case 0x8E:	printf("\"찔\", ");	break;
			case 0x8F:	printf("\"춰\", ");	break;
			case 0x90:	printf("\"퀴\", ");	break;
			case 0x91:	printf("\"킨\", ");	break;
			case 0x92:	printf("\"태\", ");	break;
			case 0x93:	printf("\"표\", ");	break;
			case 0x94:	printf("\"허\", ");	break;
			case 0x95:	printf("\"황\", ");	break;
			case 0x96:	printf("\"훗\", ");	break;
			case 0x97:	printf("\"흘\", ");	break;
			case 0x98:	printf("\"흥\", ");	break;
			case 0x99:	printf("\"갱\", ");	break;
			case 0x9A:	printf("\"극\", ");	break;
			case 0x9B:	printf("\"급\", ");	break;
			case 0x9C:	printf("\"꺼\", ");	break;
			case 0x9D:	printf("\"끈\", ");	break;
			case 0x9E:	printf("\"끌\", ");	break;
			case 0x9F:	printf("\"낭\", ");	break;
			case 0xA0:	printf("\"늦\", ");	break;
			case 0xA1:	printf("\"닙\", ");	break;
			case 0xA2:	printf("\"덮\", ");	break;
			case 0xA3:	printf("\"딜\", ");	break;
			case 0xA4:	printf("\"랑\", ");	break;
			case 0xA5:	printf("\"럭\", ");	break;
			case 0xA6:	printf("\"렀\", ");	break;
			case 0xA7:	printf("\"륭\", ");	break;
			case 0xA8:	printf("\"립\", ");	break;
			case 0xA9:	printf("\"맙\", ");	break;
			case 0xAA:	printf("\"멀\", ");	break;
			case 0xAB:	printf("\"몇\", ");	break;
			case 0xAC:	printf("\"묘\", ");	break;
			case 0xAD:	printf("\"믹\", ");	break;
			case 0xAE:	printf("\"범\", ");	break;
			case 0xAF:	printf("\"벗\", ");	break;
			case 0xB0:	printf("\"본\", ");	break;
			case 0xB1:	printf("\"뽀\", ");	break;
			case 0xB2:	printf("\"뽑\", ");	break;
			case 0xB3:	printf("\"숙\", ");	break;
			case 0xB4:	printf("\"숴\", ");	break;
			case 0xB5:	printf("\"쌓\", ");	break;
			case 0xB6:	printf("\"쎄\", ");	break;
			case 0xB7:	printf("\"앉\", ");	break;
			case 0xB8:	printf("\"옛\", ");	break;
			case 0xB9:	printf("\"옵\", ");	break;
			case 0xBA:	printf("\"왔\", ");	break;
			case 0xBB:	printf("\"읽\", ");	break;
			case 0xBC:	printf("\"잊\", ");	break;
			case 0xBD:	printf("\"접\", ");	break;
			case 0xBE:	printf("\"죄\", ");	break;
			case 0xBF:	printf("\"쩝\", ");	break;
			case 0xC0:	printf("\"쫏\", ");	break;
			case 0xC1:	printf("\"쭈\", ");	break;
			case 0xC2:	printf("\"켰\", ");	break;
			case 0xC3:	printf("\"콕\", ");	break;
			case 0xC4:	printf("\"쿄\", ");	break;
			case 0xC5:	printf("\"큼\", ");	break;
			case 0xC6:	printf("\"킹\", ");	break;
			case 0xC7:	printf("\"땀\", ");	break;
			case 0xC8:	printf("\"땁\", ");	break;
			case 0xC9:	printf("\"땃\", ");	break;
			case 0xCA:	printf("\"퍽\", ");	break;
			case 0xCB:	printf("\"폭\", ");	break;
			case 0xCC:	printf("\"푹\", ");	break;
			case 0xCD:	printf("\"풀\", ");	break;
			case 0xCE:	printf("\"효\", ");	break;
			case 0xCF:	printf("\"훔\", ");	break;
			case 0xD0:	printf("\"값\", ");	break;
			case 0xD1:	printf("\"걀\", ");	break;
			case 0xD2:	printf("\"겐\", ");	break;
			case 0xD3:	printf("\"겝\", ");	break;
			case 0xD4:	printf("\"광\", ");	break;
			case 0xD5:	printf("\"굳\", ");	break;
			case 0xD6:	printf("\"깃\", ");	break;
			case 0xD7:	printf("\"껄\", ");	break;
			case 0xD8:	printf("\"꽁\", ");	break;
			case 0xD9:	printf("\"꽤\", ");	break;
			case 0xDA:	printf("\"끊\", ");	break;
			case 0xDB:	printf("\"넉\", ");	break;
			case 0xDC:	printf("\"널\", ");	break;
			case 0xDD:	printf("\"넨\", ");	break;
			case 0xDE:	printf("\"념\", ");	break;
			case 0xDF:	printf("\"녕\", ");	break;
			case 0xE0:	printf("\"뉘\", ");	break;
			case 0xE1:	printf("\"늑\", ");	break;
			case 0xE2:	printf("\"닐\", ");	break;
			case 0xE3:	printf("\"닦\", ");	break;
			case 0xE4:	printf("\"담\", ");	break;
			case 0xE5:	printf("\"닷\", ");	break;
			case 0xE6:	printf("\"뒀\", ");	break;
			case 0xE7:	printf("\"득\", ");	break;
			case 0xE8:	printf("\"땡\", ");	break;
			case 0xE9:	printf("\"똑\", ");	break;
			case 0xEA:	printf("\"뜩\", ");	break;
			case 0xEB:	printf("\"뜬\", ");	break;
			case 0xEC:	printf("\"랄\", ");	break;
			case 0xED:	printf("\"랍\", ");	break;
			case 0xEE:	kanji = 1;break;
			case 0xEF:	kanji = 2;	break;
			case 0xF0:	kanji = 3;	break;

			case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
			case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
			case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
			case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
			case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
			case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
			case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
			case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
			case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
			case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
			case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
			case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
			case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
			case 0xFE:  printf("\" \", ");	raw = 0; break;
			case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;

			default:    printf("0x%X, ", d[0]);
			}
			kanji = 0;
			}
			else if (kanji == 3)
			{
			switch (d[0])
			{
			case 0x00:	printf("\"랏\", ");	break;
			case 0x01:	printf("\"렵\", ");	break;
			case 0x02:	printf("\"론\", ");	break;
			case 0x03:	printf("\"룩\", ");	break;
			case 0x04:	printf("\"류\", ");	break;
			case 0x05:	printf("\"맹\", ");	break;
			case 0x06:	printf("\"먼\", ");	break;
			case 0x07:	printf("\"멸\", ");	break;
			case 0x08:	printf("\"몬\", ");	break;
			case 0x09:	printf("\"묵\", ");	break;
			case 0x0A:	printf("\"뭣\", ");	break;
			case 0x0B:	printf("\"므\", ");	break;
			case 0x0C:	printf("\"밍\", ");	break;
			case 0x0D:	printf("\"밭\", ");	break;
			case 0x0E:	printf("\"뱃\", ");	break;
			case 0x0F:	printf("\"봉\", ");	break;
			case 0x10:	printf("\"뵈\", ");	break;
			case 0x11:	printf("\"빈\", ");	break;
			case 0x12:	printf("\"뻥\", ");	break;
			case 0x13:	printf("\"쁘\", ");	break;
			case 0x14:	printf("\"쁜\", ");	break;
			case 0x15:	printf("\"삶\", ");	break;
			case 0x16:	printf("\"샀\", ");	break;
			case 0x17:	printf("\"센\", ");	break;
			case 0x18:	printf("\"슬\", ");	break;
			case 0x19:	printf("\"쑤\", ");	break;
			case 0x1A:	printf("\"액\", ");	break;
			case 0x1B:	printf("\"얽\", ");	break;
			case 0x1C:	printf("\"엇\", ");	break;
			case 0x1D:	printf("\"엉\", ");	break;
			case 0x1E:	printf("\"엣\", ");	break;
			case 0x1F:	printf("\"웠\", ");	break;
			case 0x20:	printf("\"원\", ");	break;
			case 0x21:	printf("\"쫍\", ");	break;
			case 0x22:	printf("\"쥐\", ");	break;
			case 0x23:	printf("\"징\", ");	break;
			case 0x24:	printf("\"찰\", ");	break;
			case 0x25:	printf("\"챠\", ");	break;
			case 0x26:	printf("\"콜\", ");	break;
			case 0x27:	printf("\"쾌\", ");	break;
			case 0x28:	printf("\"떡\", ");	break;
			case 0x29:	printf("\"떨\", ");	break;
			case 0x2A:	printf("\"토\", ");	break;
			case 0x2B:	printf("\"팻\", ");	break;
			case 0x2C:	printf("\"페\", ");	break;
			case 0x2D:	printf("\"푼\", ");	break;
			case 0x2E:	printf("\"헷\", ");	break;
			case 0x2F:	printf("\"협\", ");	break;
			case 0x30:	printf("\"혔\", ");	break;
			case 0x31:	printf("\"휴\", ");	break;
			case 0x32:	printf("\"흥\", ");	break;
			case 0x33:	printf("\"갇\", ");	break;
			case 0x34:	printf("\"갚\", ");	break;
			case 0x35:	printf("\"걷\", ");	break;
			case 0x36:	printf("\"겉\", ");	break;
			case 0x37:	printf("\"굽\", ");	break;
			case 0x38:	printf("\"김\", ");	break;
			case 0x39:	printf("\"깍\", ");	break;
			case 0x3A:	printf("\"깜\", ");	break;
			case 0x3B:	printf("\"깥\", ");	break;
			case 0x3C:	printf("\"깬\", ");	break;
			case 0x3D:	printf("\"꺄\", ");	break;
			case 0x3E:	printf("\"껏\", ");	break;
			case 0x3F:	printf("\"껴\", ");	break;
			case 0x40:	printf("\"꽃\", ");	break;
			case 0x41:	printf("\"꾼\", ");	break;
			case 0x42:	printf("\"꿇\", ");	break;
			case 0x43:	printf("\"꿨\", ");	break;
			case 0x44:	printf("\"끄\", ");	break;
			case 0x45:	printf("\"낫\", ");	break;
			case 0x46:	printf("\"낮\", ");	break;
			case 0x47:	printf("\"낯\", ");	break;
			case 0x48:	printf("\"낱\", ");	break;
			case 0x49:	printf("\"넵\", ");	break;
			case 0x4A:	printf("\"넓\", ");	break;
			case 0x4B:	printf("\"넛\", ");	break;
			case 0x4C:	printf("\"년\", ");	break;
			case 0x4D:	printf("\"높\", ");	break;
			case 0x4E:	printf("\"뇽\", ");	break;
			case 0x4F:	printf("\"눌\", ");	break;
			case 0x50:	printf("\"뉴\", ");	break;
			case 0x51:	printf("\"늙\", ");	break;
			case 0x52:	printf("\"닭\", ");	break;
			case 0x53:	printf("\"닮\", ");	break;
			case 0x54:	printf("\"댈\", ");	break;
			case 0x55:	printf("\"댕\", ");	break;
			case 0x56:	printf("\"덧\", ");	break;
			case 0x57:	printf("\"덫\", ");	break;
			case 0x58:	printf("\"둘\", ");	break;
			case 0x59:	printf("\"뒷\", ");	break;
			case 0x5A:	printf("\"듬\", ");	break;
			case 0x5B:	printf("\"듭\", ");	break;
			case 0x5C:	printf("\"등\", ");	break;
			case 0x5D:	printf("\"딥\", ");	break;
			case 0x5E:	printf("\"딱\", ");	break;
			case 0x5F:	printf("\"땠\", ");	break;
			case 0x60:	printf("\"떡\", ");	break;
			case 0x61:	printf("\"떼\", ");	break;
			case 0x62:	printf("\"랬\", ");	break;
			case 0x63:	printf("\"량\", ");	break;
			case 0x64:	printf("\"렴\", ");	break;
			case 0x65:	printf("\"롱\", ");	break;
			case 0x66:	printf("\"륙\", ");	break;
			case 0x67:	printf("\"릎\", ");	break;
			case 0x68:	printf("\"맑\", ");	break;
			case 0x69:	printf("\"맷\", ");	break;
			case 0x6A:	printf("\"멈\", ");	break;
			case 0x6B:	printf("\"몫\", ");	break;
			case 0x6C:	printf("\"묶\", ");	break;
			case 0x6D:	printf("\"뭘\", ");	break;
			case 0x6E:	printf("\"민\", ");	break;
			case 0x6F:	printf("\"밌\", ");	break;
			case 0x70:	printf("\"밟\", ");	break;
			case 0x71:	printf("\"밧\", ");	break;
			case 0x72:	printf("\"백\", ");	break;
			case 0x73:	printf("\"벅\", ");	break;
			case 0x74:	printf("\"벤\", ");	break;
			case 0x75:	printf("\"벨\", ");	break;
			case 0x76:	printf("\"뻐\", ");	break;
			case 0x77:	printf("\"뻔\", ");	break;
			case 0x78:	printf("\"뿔\", ");	break;
			case 0x79:	printf("\"삯\", ");	break;
			case 0x7A:	printf("\"삽\", ");	break;
			case 0x7B:	printf("\"섭\", ");	break;
			case 0x7C:	printf("\"셜\", ");	break;
			case 0x7D:	printf("\"솔\", ");	break;
			case 0x7E:	printf("\"숫\", ");	break;
			case 0x7F:	printf("\"싱\", ");	break;
			case 0x80:	printf("\"썰\", ");	break;
			case 0x81:	printf("\"썼\", ");	break;
			case 0x82:	printf("\"쏘\", ");	break;
			case 0x83:	printf("\"쑥\", ");	break;
			case 0x84:	printf("\"씌\", ");	break;
			case 0x85:	printf("\"앙\", ");	break;
			case 0x86:	printf("\"얏\", ");	break;
			case 0x87:	printf("\"엎\", ");	break;
			case 0x88:	printf("\"엑\", ");	break;
			case 0x89:	printf("\"엽\", ");	break;
			case 0x8A:	printf("\"엿\", ");	break;
			case 0x8B:	printf("\"월\", ");	break;
			case 0x8C:	printf("\"윗\", ");	break;
			case 0x8D:	printf("\"육\", ");	break;
			case 0x8E:	printf("\"쟀\", ");	break;
			case 0x8F:	printf("\"젊\", ");	break;
			case 0x90:	printf("\"젓\", ");	break;
			case 0x91:	printf("\"줍\", ");	break;
			case 0x92:	printf("\"즐\", ");	break;
			case 0x93:	printf("\"증\", ");	break;
			case 0x94:	printf("\"짖\", ");	break;
			case 0x95:	printf("\"짝\", ");	break;
			case 0x96:	printf("\"짱\", ");	break;
			case 0x97:	printf("\"쨍\", ");	break;
			case 0x98:	printf("\"쩜\", ");	break;
			case 0x99:	printf("\"쩡\", ");	break;
			case 0x9A:	printf("\"쪼\", ");	break;
			case 0x9B:	printf("\"쭉\", ");	break;
			case 0x9C:	printf("\"찍\", ");	break;
			case 0x9D:	printf("\"쳐\", ");	break;
			case 0x9E:	printf("\"쳤\", ");	break;
			case 0x9F:	printf("\"촌\", ");	break;
			case 0xA0:	printf("\"칭\", ");	break;
			case 0xA1:	printf("\"컴\", ");	break;
			case 0xA2:	printf("\"켁\", ");	break;
			case 0xA3:	printf("\"콩\", ");	break;
			case 0xA4:	printf("\"쿨\", ");	break;
			case 0xA5:	printf("\"큭\", ");	break;
			case 0xA6:	printf("\"킥\", ");	break;
			case 0xA7:	printf("\"탄\", ");	break;
			case 0xA8:	printf("\"탱\", ");	break;
			case 0xA9:	printf("\"턴\", ");	break;
			case 0xAA:	printf("\"텅\", ");	break;
			case 0xAB:	printf("\"특\", ");	break;
			case 0xAC:	printf("\"팩\", ");	break;
			case 0xAD:	printf("\"펀\", ");	break;
			case 0xAE:	printf("\"펜\", ");	break;
			case 0xAF:	printf("\"펴\", ");	break;
			case 0xB0:	printf("\"폐\", ");	break;
			case 0xB1:	printf("\"풍\", ");	break;
			case 0xB2:	printf("\"화\", ");	break;
			case 0xB3:	printf("\"흰\", ");	break;

			case 0xEE:	kanji = 1; break;
			case 0xEF:	kanji = 2;	break;
			case 0xF0:	kanji = 3;	break;

			case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
			case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
			case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
			case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
			case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
			case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
			case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
			case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
			case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
			case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
			case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
			case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
			case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
			case 0xFE:  printf("\" \", ");	raw = 0; break;
			case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;

			default:    printf("0x%X, ", d[0]);
			}
			kanji = 0;
			}
			/*
			else if (bigfont==1)
			{
				switch (d[0])
				{
				case 0x00:	printf("\"<タ>\", ");	break;
				case 0x01:	printf("\"<ダ>\", ");	break;
				case 0x02:	printf("\"<ゲ>\", ");	break;
				case 0x03:	printf("\"<ッ>\", ");	break;
				case 0x04:	printf("\"<！>\", ");	break;
				case 0x05:	printf("\"<？>\", ");	break;
				case 0x06:	printf("\"<な>\", ");	break;
				case 0x07:	printf("\"<に>\", ");	break;
				case 0x08:	printf("\"<一>\", ");	break;
				case 0x09:	printf("\"<っ>\", ");	break;
				case 0x0A:	printf("\"<許>\", ");	break;
				case 0x0B:	printf("\"<せ>\", ");	break;
				case 0x0C:	printf("\"<ん>\", ");	break;
				case 0x0D:	printf("\"<ス>\", ");	break;
				case 0x0E:	printf("\"<ポ>\", ");	break;
				case 0x0F:	printf("\"<ア>\", ");	break;
				case 0x10:	printf("\"<～>\", ");	break;
				case 0x11:	printf("\"<レ>\", ");	break;
				case 0x12:	printf("\"<Z>\", ");	break;
				case 0x13:	printf("\"<‥>\", ");	break;
				case 0x14:	printf("\"<ギ>\", ");	break;
				case 0x15:	printf("\"<ャ>\", ");	break;
				case 0x16:	printf("\"<ぐ>\", ");	break;
				case 0x17:	printf("\"<わ>\", ");	break;
				case 0x18:	printf("\"<同>\", ");	break;
				case 0x19:	printf("\"<じ>\", ");	break;
				case 0x1A:	printf("\"<の>\", ");	break;
				case 0x1B:	printf("\"<し>\", ");	break;
				case 0x1C:	printf("\"<ハ>\", ");	break;
				case 0x1D:	printf("\"<ウ>\", ");	break;
				case 0x1E:	printf("\"<ワ>\", ");	break;
				case 0x1F:	printf("\"<ぁ>\", ");	break;

				case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
				case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
				case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
				case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
				case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
				case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
				case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
				case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
				case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
				case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
				case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
				case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
				case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
				case 0xFE:  printf("\" \", ");	raw = 0; break;
				case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;
				default:    printf("0x%X, ", d[0]);
				}
			}
			else if (kanji == 0)
			{
				switch (d[0])
				{
				case 0x00:	printf("\"あ\", ");	break;
				case 0x01:	printf("\"い\", ");	break;
				case 0x02:	printf("\"う\", ");	break;
				case 0x03:	printf("\"え\", ");	break;
				case 0x04:	printf("\"お\", ");	break;
				case 0x05:	printf("\"か\", ");	break;
				case 0x06:	printf("\"き\", ");	break;
				case 0x07:	printf("\"く\", ");	break;
				case 0x08:	printf("\"け\", ");	break;
				case 0x09:	printf("\"こ\", ");	break;
				case 0x0A:	printf("\"さ\", ");	break;
				case 0x0B:	printf("\"し\", ");	break;
				case 0x0C:	printf("\"す\", ");	break;
				case 0x0D:	printf("\"せ\", ");	break;
				case 0x0E:	printf("\"そ\", ");	break;
				case 0x0F:	printf("\"た\", ");	break;
				case 0x10:	printf("\"ち\", ");	break;
				case 0x11:	printf("\"つ\", ");	break;
				case 0x12:	printf("\"て\", ");	break;
				case 0x13:	printf("\"と\", ");	break;
				case 0x14:	printf("\"な\", ");	break;
				case 0x15:	printf("\"に\", ");	break;
				case 0x16:	printf("\"ぬ\", ");	break;
				case 0x17:	printf("\"ね\", ");	break;
				case 0x18:	printf("\"の\", ");	break;
				case 0x19:	printf("\"は\", ");	break;
				case 0x1A:	printf("\"ひ\", ");	break;
				case 0x1B:	printf("\"ふ\", ");	break;
				case 0x1C:	printf("\"へ\", ");	break;
				case 0x1D:	printf("\"ほ\", ");	break;
				case 0x1E:	printf("\"ま\", ");	break;
				case 0x1F:	printf("\"み\", ");	break;
				case 0x20:	printf("\"む\", ");	break;
				case 0x21:	printf("\"め\", ");	break;
				case 0x22:	printf("\"も\", ");	break;
				case 0x23:	printf("\"や\", ");	break;
				case 0x24:	printf("\"ゆ\", ");	break;
				case 0x25:	printf("\"よ\", ");	break;
				case 0x26:	printf("\"ら\", ");	break;
				case 0x27:	printf("\"り\", ");	break;
				case 0x28:	printf("\"る\", ");	break;
				case 0x29:	printf("\"れ\", ");	break;
				case 0x2A:	printf("\"ろ\", ");	break;
				case 0x2B:	printf("\"わ\", ");	break;
				case 0x2C:	printf("\"を\", ");	break;
				case 0x2D:	printf("\"ん\", ");	break;
				case 0x2E:	printf("\"ぁ\", ");	break;
				case 0x2F:	printf("\"ぃ\", ");	break;
				case 0x30:	printf("\"ぅ\", ");	break;
				case 0x31:	printf("\"ぇ\", ");	break;
				case 0x32:	printf("\"ぉ\", ");	break;
				case 0x33:	printf("\"ゃ\", ");	break;
				case 0x34:	printf("\"ゅ\", ");	break;
				case 0x35:	printf("\"ょ\", ");	break;
				case 0x36:	printf("\"っ\", ");	break;
				case 0x37:	printf("\"が\", ");	break;
				case 0x38:	printf("\"ぎ\", ");	break;
				case 0x39:	printf("\"ぐ\", ");	break;
				case 0x3A:	printf("\"げ\", ");	break;
				case 0x3B:	printf("\"ご\", ");	break;
				case 0x3C:	printf("\"ざ\", ");	break;
				case 0x3D:	printf("\"じ\", ");	break;
				case 0x3E:	printf("\"ず\", ");	break;
				case 0x3F:	printf("\"ぜ\", ");	break;
				case 0x40:	printf("\"ぞ\", ");	break;
				case 0x41:	printf("\"だ\", ");	break;
				case 0x42:	printf("\"ぢ\", ");	break;
				case 0x43:	printf("\"づ\", ");	break;
				case 0x44:	printf("\"で\", ");	break;
				case 0x45:	printf("\"ど\", ");	break;
				case 0x46:	printf("\"ば\", ");	break;
				case 0x47:	printf("\"び\", ");	break;
				case 0x48:	printf("\"ぶ\", ");	break;
				case 0x49:	printf("\"べ\", ");	break;
				case 0x4A:	printf("\"ぼ\", ");	break;
				case 0x4B:	printf("\"ぱ\", ");	break;
				case 0x4C:	printf("\"ぴ\", ");	break;
				case 0x4D:	printf("\"ぷ\", ");	break;
				case 0x4E:	printf("\"ぺ\", ");	break;
				case 0x4F:	printf("\"ぽ\", ");	break;
				case 0x50:	printf("\"ア\", ");	break;
				case 0x51:	printf("\"イ\", ");	break;
				case 0x52:	printf("\"ウ\", ");	break;
				case 0x53:	printf("\"エ\", ");	break;
				case 0x54:	printf("\"オ\", ");	break;
				case 0x55:	printf("\"カ\", ");	break;
				case 0x56:	printf("\"キ\", ");	break;
				case 0x57:	printf("\"ク\", ");	break;
				case 0x58:	printf("\"ケ\", ");	break;
				case 0x59:	printf("\"コ\", ");	break;
				case 0x5A:	printf("\"サ\", ");	break;
				case 0x5B:	printf("\"シ\", ");	break;
				case 0x5C:	printf("\"ス\", ");	break;
				case 0x5D:	printf("\"セ\", ");	break;
				case 0x5E:	printf("\"ソ\", ");	break;
				case 0x5F:	printf("\"タ\", ");	break;
				case 0x60:	printf("\"チ\", ");	break;
				case 0x61:	printf("\"ツ\", ");	break;
				case 0x62:	printf("\"テ\", ");	break;
				case 0x63:	printf("\"ト\", ");	break;
				case 0x64:	printf("\"ナ\", ");	break;
				case 0x65:	printf("\"ニ\", ");	break;
				case 0x66:	printf("\"ヌ\", ");	break;
				case 0x67:	printf("\"ネ\", ");	break;
				case 0x68:	printf("\"ノ\", ");	break;
				case 0x69:	printf("\"ハ\", ");	break;
				case 0x6A:	printf("\"ヒ\", ");	break;
				case 0x6B:	printf("\"フ\", ");	break;
				case 0x6C:	printf("\"ヘ\", ");	break;
				case 0x6D:	printf("\"ホ\", ");	break;
				case 0x6E:	printf("\"マ\", ");	break;
				case 0x6F:	printf("\"ミ\", ");	break;
				case 0x70:	printf("\"ム\", ");	break;
				case 0x71:	printf("\"メ\", ");	break;
				case 0x72:	printf("\"モ\", ");	break;
				case 0x73:	printf("\"ヤ\", ");	break;
				case 0x74:	printf("\"ユ\", ");	break;
				case 0x75:	printf("\"ヨ\", ");	break;
				case 0x76:	printf("\"ラ\", ");	break;
				case 0x77:	printf("\"リ\", ");	break;
				case 0x78:	printf("\"ル\", ");	break;
				case 0x79:	printf("\"レ\", ");	break;
				case 0x7A:	printf("\"ロ\", ");	break;
				case 0x7B:	printf("\"ワ\", ");	break;
				case 0x7C:	printf("\"ヲ\", ");	break;
				case 0x7D:	printf("\"ン\", ");	break;
				case 0x7E:	printf("\"ァ\", ");	break;
				case 0x7F:	printf("\"ィ\", ");	break;
				case 0x80:	printf("\"ゥ\", ");	break;
				case 0x81:	printf("\"ェ\", ");	break;
				case 0x82:	printf("\"ォ\", ");	break;
				case 0x83:	printf("\"ャ\", ");	break;
				case 0x84:	printf("\"ュ\", ");	break;
				case 0x85:	printf("\"ョ\", ");	break;
				case 0x86:	printf("\"ッ\", ");	break;
				case 0x87:	printf("\"ガ\", ");	break;
				case 0x88:	printf("\"ギ\", ");	break;
				case 0x89:	printf("\"グ\", ");	break;
				case 0x8A:	printf("\"ゲ\", ");	break;
				case 0x8B:	printf("\"ゴ\", ");	break;
				case 0x8C:	printf("\"ザ\", ");	break;
				case 0x8D:	printf("\"ジ\", ");	break;
				case 0x8E:	printf("\"ズ\", ");	break;
				case 0x8F:	printf("\"ゼ\", ");	break;
				case 0x90:	printf("\"ゾ\", ");	break;
				case 0x91:	printf("\"ダ\", ");	break;
				case 0x92:	printf("\"ヂ\", ");	break;
				case 0x93:	printf("\"ヅ\", ");	break;
				case 0x94:	printf("\"デ\", ");	break;
				case 0x95:	printf("\"ド\", ");	break;
				case 0x96:	printf("\"バ\", ");	break;
				case 0x97:	printf("\"ビ\", ");	break;
				case 0x98:	printf("\"ブ\", ");	break;
				case 0x99:	printf("\"ベ\", ");	break;
				case 0x9A:	printf("\"ボ\", ");	break;
				case 0x9B:	printf("\"パ\", ");	break;
				case 0x9C:	printf("\"ピ\", ");	break;
				case 0x9D:	printf("\"プ\", ");	break;
				case 0x9E:	printf("\"ペ\", ");	break;
				case 0x9F:	printf("\"ポ\", ");	break;
				case 0xA0:	printf("\"~\", ");	break;
				case 0xA1:	printf("\"！\", ");	break;
				case 0xA2:	printf("\"？\", ");	break;
				case 0xA3:	printf("\"－\", ");	break;
				case 0xA4:	printf("\".\", ");	break;
				case 0xA5:	printf("\"‥\", ");	break;
				case 0xA6:	printf("\"♡\", ");	break;
				case 0xA7:	printf("\"&\", ");	break;
				case 0xA8:	printf("\"、\", ");	break;
				case 0xA9:	printf("\"。\", ");	break;
				case 0xAA:	printf("\"(\", ");	break;
				case 0xAB:	printf("\")\", ");	break;
				case 0xAC:	printf("\"○\", ");	break;
				case 0xAD:	printf("\"×\", ");	break;
				case 0xAE:	printf("\"△\", ");	break;
				case 0xAF:	printf("\"_\", ");	break;
				case 0xB0:	printf("\"A\", ");	break;
				case 0xB1:	printf("\"B\", ");	break;
				case 0xB2:	printf("\"C\", ");	break;
				case 0xB3:	printf("\"D\", ");	break;
				case 0xB4:	printf("\"E\", ");	break;
				case 0xB5:	printf("\"F\", ");	break;
				case 0xB6:	printf("\"G\", ");	break;
				case 0xB7:	printf("\"H\", ");	break;
				case 0xB8:	printf("\"I\", ");	break;
				case 0xB9:	printf("\"J\", ");	break;
				case 0xBA:	printf("\"K\", ");	break;
				case 0xBB:	printf("\"L\", ");	break;
				case 0xBC:	printf("\"M\", ");	break;
				case 0xBD:	printf("\"N\", ");	break;
				case 0xBE:	printf("\"O\", ");	break;
				case 0xBF:	printf("\"P\", ");	break;
				case 0xC0:	printf("\"Q\", ");	break;
				case 0xC1:	printf("\"R\", ");	break;
				case 0xC2:	printf("\"S\", ");	break;
				case 0xC3:	printf("\"T\", ");	break;
				case 0xC4:	printf("\"U\", ");	break;
				case 0xC5:	printf("\"V\", ");	break;
				case 0xC6:	printf("\"W\", ");	break;
				case 0xC7:	printf("\"X\", ");	break;
				case 0xC8:	printf("\"Y\", ");	break;
				case 0xC9:	printf("\"Z\", ");	break;
				case 0xCA:	printf("\"-\", ");	break;
				case 0xCB:	printf("\"-\", ");	break;
				case 0xCC:	printf("\"-\", ");	break;
				case 0xCD:	printf("\"▼\", ");	break;
				case 0xCE:	printf("\"「\", ");	break;
				case 0xCF:	printf("\"」\", ");	break;
				case 0xD0:	printf("\"0\", ");	break;
				case 0xD1:	printf("\"1\", ");	break;
				case 0xD2:	printf("\"2\", ");	break;
				case 0xD3:	printf("\"3\", ");	break;
				case 0xD4:	printf("\"4\", ");	break;
				case 0xD5:	printf("\"5\", ");	break;
				case 0xD6:	printf("\"6\", ");	break;
				case 0xD7:	printf("\"7\", ");	break;
				case 0xD8:	printf("\"8\", ");	break;
				case 0xD9:	printf("\"9\", ");	break;

				case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
				case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
				case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
				case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
				case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
				case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
				case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
				case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
				case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
				case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
				case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
				case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
				case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
				case 0xFE:  printf("\" \", ");	raw = 0; break;
				case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;
				
				default:    printf("0x%X, ", d[0]);
				}
			}
			else if (kanji == 1)
			{
				switch (d[0])
				{
				case 0x00:	printf("\"同\", ");	break;
				case 0x01:	printf("\"代\", ");	break;
				case 0x02:	printf("\"安\", ");	break;
				case 0x03:	printf("\"京\", ");	break;
				case 0x04:	printf("\"氷\", ");	break;
				case 0x05:	printf("\"河\", ");	break;
				case 0x06:	printf("\"王\", ");	break;
				case 0x07:	printf("\"子\", ");	break;
				case 0x08:	printf("\"巨\", ");	break;
				case 0x09:	printf("\"人\", ");	break;
				case 0x0A:	printf("\"<KANJI0A>\", ");	break; //々
				case 0x0B:	printf("\"山\", ");	break;
				case 0x0C:	printf("\"時\", ");	break;
				case 0x0D:	printf("\"心\", ");	break;
				case 0x0E:	printf("\"大\", ");	break;
				case 0x0F:	printf("\"岩\", ");	break;
				case 0x10:	printf("\"日\", ");	break;
				case 0x11:	printf("\"回\", ");	break;
				case 0x12:	printf("\"火\", ");	break;
				case 0x13:	printf("\"水\", ");	break;
				case 0x14:	printf("\"木\", ");	break;
				case 0x15:	printf("\"年\", ");	break;
				case 0x16:	printf("\"上\", ");	break;
				case 0x17:	printf("\"下\", ");	break;
				case 0x18:	printf("\"平\", ");	break;
				case 0x19:	printf("\"和\", ");	break;
				case 0x1A:	printf("\"左\", ");	break;
				case 0x1B:	printf("\"右\", ");	break;
				case 0x1C:	printf("\"東\", ");	break;
				case 0x1D:	printf("\"西\", ");	break;
				case 0x1E:	printf("\"南\", ");	break;
				case 0x1F:	printf("\"北\", ");	break;
				case 0x20:	printf("\"國\", ");	break;
				case 0x21:	printf("\"女\", ");	break;
				case 0x22:	printf("\"姬\", ");	break;
				case 0x23:	printf("\"金\", ");	break;
				case 0x24:	printf("\"小\", ");	break;
				case 0x25:	printf("\"中\", ");	break;
				case 0x26:	printf("\"行\", ");	break;
				case 0x27:	printf("\"百\", ");	break;
				case 0x28:	printf("\"十\", ");	break;
				case 0x29:	printf("\"千\", ");	break;
				case 0x2A:	printf("\"万\", ");	break;
				case 0x2B:	printf("\"愛\", ");	break;
				case 0x2C:	printf("\"身\", ");	break;
				case 0x2D:	printf("\"申\", ");	break;
				case 0x2E:	printf("\"二\", ");	break;
				case 0x2F:	printf("\"町\", ");	break;
				case 0x30:	printf("\"所\", ");	break;
				case 0x31:	printf("\"今\", ");	break;
				case 0x32:	printf("\"力\", ");	break;
				case 0x33:	printf("\"村\", ");	break;
				case 0x34:	printf("\"店\", ");	break;
				case 0x35:	printf("\"用\", ");	break;
				case 0x36:	printf("\"手\", ");	break;
				case 0x37:	printf("\"先\", ");	break;
				case 0x38:	printf("\"目\", ");	break;
				case 0x39:	printf("\"<KANJI39>\", ");	break;//乱
				case 0x3A:	printf("\"私\", ");	break;
				case 0x3B:	printf("\"友\", ");	break;
				case 0x3C:	printf("\"井\", ");	break;
				case 0x3D:	printf("\"<KANJI3D>\", ");	break; //户
				case 0x3E:	printf("\"元\", ");	break;
				case 0x3F:	printf("\"必\", ");	break;
				case 0x40:	printf("\"<KANJI40>\", ");	break;// 凮
				case 0x41:	printf("\"<KANJI41>\", ");	break;// 权
				case 0x42:	printf("\"正\", ");	break;
				case 0x43:	printf("\"本\", ");	break;
				case 0x44:	printf("\"自\", ");	break;
				case 0x45:	printf("\"分\", ");	break;
				case 0x46:	printf("\"氣\", ");	break;
				case 0x47:	printf("\"失\", ");	break;
				case 0x48:	printf("\"死\", ");	break;
				case 0x49:	printf("\"入\", ");	break;
				case 0x4A:	printf("\"匹\", ");	break;
				case 0x4B:	printf("\"穴\", ");	break;
				case 0x4C:	printf("\"缶\", ");	break;
				case 0x4D:	printf("\"詰\", ");	break;
				case 0x4E:	printf("\"兵\", ");	break;
				case 0x4F:	printf("\"士\", ");	break;
				case 0x50:	printf("\"少\", ");	break;
				case 0x51:	printf("\"以\", ");	break;
				case 0x52:	printf("\"出\", ");	break;
				case 0x53:	printf("\"我\", ");	break;
				case 0x54:	printf("\"忍\", ");	break;
				case 0x55:	printf("\"近\", ");	break;
				case 0x56:	printf("\"<KANJI56>\", ");	break;//当
				case 0x57:	printf("\"湖\", ");	break;
				case 0x58:	printf("\"內\", ");	break;
				case 0x59:	printf("\"外\", ");	break;
				case 0x5A:	printf("\"海\", ");	break;
				case 0x5B:	printf("\"全\", ");	break;
				case 0x5C:	printf("\"主\", ");	break;
				case 0x5D:	printf("\"方\", ");	break;
				case 0x5E:	printf("\"向\", ");	break;
				case 0x5F:	printf("\"字\", ");	break;
				case 0x60:	printf("\"ヶ\", ");	break;
				case 0x61:	printf("\"記\", ");	break;
				case 0x62:	printf("\"世\", ");	break;
				case 0x63:	printf("\"<KANJI63>\", ");	break;//宝
				case 0x64:	printf("\"法\", ");	break;
				case 0x65:	printf("\"口\", ");	break;

				case 0xF1:  printf("\"<FUNCTION_F1>\", ");  raw = 1; break;
				case 0xF2:  printf("\"<FUNCTION_F2>\", ");  raw = 0; break;
				case 0xF3:  printf("\"<KANJI_END>\", ");    raw = 0; kanji = 0;  break;
				case 0xF4:  printf("\"<KANJI_START>\", ");  raw = 0; kanji = 1;  break;
				case 0xF5:  printf("\"<FUNCTION_F5>\", ");  raw = 1;   break;
				case 0xF6:  printf("\"<FUNCTION_F6>\", ");  raw = 1;  break;
				case 0xF7:  printf("\"<BIG_FONT>\", ");     raw = 0; bigfont = 1;  break;
				case 0xF8:  printf("\"<FUNCTION_F8>\", ");  raw = 1; break;
				case 0xF9:  printf("\"<FUNCTION_F9>\", ");  raw = 1; break;
				case 0xFA:  printf("\"<FUNCTION_FA>\", ");  raw = 1; break;
				case 0xFB:  printf("\"<FUNCTION_FB>\", ");  raw = 1; break;
				case 0xFC:  printf("\"<FUNCTION_FC>\", ");  raw = 1; break;
				case 0xFD:  printf("\"<LINE_CHANGE>\"\ndb , "); raw = 0; bigfont = 0;  break;
				case 0xFE:  printf("\" \", ");	raw = 0; break;
				case 0xFF:  printf("\"<LINE_END>\", ");	kanji = 0; bigfont = 0; break;
				default:    printf("0x%X, ", d[0]);
				}
			}
			*/
			
		}
		d[0] = 0x00;
		printf("\b\b \n");


	}




	return 0;
}